### ISSUE TITLE
VideoPlayer cannot play url issue

### ISSUE THREAD

**Issue by tinypawb** [Kevga/BeatSaberCinema#53] opened 2022-08-01 22:17 UTC
I am currently having an issue with Cinema not displaying videos while in-game. It worked yesterday but randomly just stopped today. I can download videos but nothing shows while playing or previewing. Tried a fresh install of all mods, updating all mods, checking dependencies, downgrading, and doing an entire reinstall on a different drive but it doesn't seem to work. For some reason though, it works on an old install I made a while ago of 1.19 that already had Cinema installed. For every new install I make however, it has the same issue. 

Windows hasn't updated since last play

The only major thing I have done since play sessions was upgrade my Nvidia graphical drivers to 516.59
[_latest.log](https://github.com/Kevga/BeatSaberCinema/files/9237703/_latest.log)

**Comment by Kevga** [comment] 2022-08-01 22:34
Duplicate of #30. Check out [this comment](https://github.com/Kevga/BeatSaberCinema/issues/30#issuecomment-937439923) in particular, maybe this works for you too.

**Closed by Kevga** 2022-08-01 22:34 UTC
