### ISSUE TITLE
Video sometimes freezes

### ISSUE THREAD

**Issue by Hexnet111** [Kevga/BeatSaberCinema#5] opened 2020-12-17 22:06 UTC
Not exactly sure why it was caused but when I might have and might not have played the entire shrek movie with the actual movie playing in the background, the video sometimes had freezes that lasted around 1 - 2 minutes. I'm not exactly sure why it was caused but I wanted to post this just incase. (Also just for context I went to the same time that it freezed and there were no freezes in the video that I could find.)

Also, would be cool if you can add support for h264 and h265 compressions.

Log:
[2020.12.14.19.57.45.log](https://github.com/Kevga/BeatSaberCinema/files/5712396/2020.12.14.19.57.45.log)

**Comment by Kevga** [comment] 2020-12-17 23:55
I asked someone who also tried to play Shrek and they had a similar experience with the freezing after a while. This honestly sounds like a nightmare to debug. I'm currently looking into replacing the video player component for unrelated reasons. I'm hopeful that this will resolve the freezing issue as a side effect.

Regarding codec support, H264 is supported already, it's the codec that pretty much all videos that get downloaded from YouTube use. H265 should in theory also be supported already, but I haven't tried that yet, as YouTube doesn't serve H265 files. It's possible that the [HEVC extensions](https://www.microsoft.com/en-us/p/hevc-video-extensions/9nmzlz57r3t7) are required for this. If I end up replacing the video player, the codec and file format support might be improved as well.

**Comment by Hexnet111** [comment] 2020-12-18 00:24
> I asked someone who also tried to play Shrek and they had a similar experience with the freezing after a while. This honestly sounds like a nightmare to debug. I'm currently looking into replacing the video player component for unrelated reasons. I'm hopeful that this will resolve the freezing issue as a side effect.
> 
> Regarding codec support, H264 is supported already, it's the codec that pretty much all videos that get downloaded from YouTube use. H265 should in theory also be supported already, but I haven't tried that yet, as YouTube doesn't serve H265 files. It's possible that the [HEVC extensions](https://www.microsoft.com/en-us/p/hevc-video-extensions/9nmzlz57r3t7) are required for this. If I end up replacing the video player, the codec and file format support might be improved as well.

I'm guessing the HEVC extension is needed, cause when I tried using the h264 codec it didn't play the video.

**Comment by Kevga** [comment] 2020-12-18 00:27
HEVC is the name of H265, the extensions would not help for H264 playback. Did you use an mkv or an mp4 container? Which combination of container and codec did you end up using that worked?

**Comment by Hexnet111** [comment] 2020-12-18 00:28
> HEVC is the name of H265, the extensions would not help for H264 playback. Did you use an mkv or an mp4 container? Which combination of container and codec did you end up using that worked?

I am not exactly sure what is the name of the codec that I ended up using but it worked. Although the compression was worse.

**Comment by Hexnet111** [comment] 2020-12-24 11:39
Also, it would be very nice if you added an option to turn off the filter that makes black colors transparent. I had many problems while playing the shrek movie, which caused me to re render the movie a couple of times and to change all of the black colors in the movie to a blueish black.

**Comment by Kevga** [comment] 2021-01-02 09:29
If I understand correctly your issue is with the color blending, which causes bright lighting from the map to drown out darker colors in the video. I experimented a bit trying to implement a variable amount of color blending, but that didn't quite work out how I would have liked. The only option I have would be to add a mode that completely disables blending, and that looks pretty terrible as well.  

I added contrast and brightness controls to the mod for a different request, those might also work in this case. Increasing brightness and decreasing contrast both would boost the darker colors of the movie. Still more of a workaround, but it probably beats having to re-render the video to turn black into blue.  

Regarding the freezing issue I wonder if that is mitigated now, since I recently implemented a re-syncing mechanism for cases where the video drifts out of sync. A freeze might cause a re-sync to occur, which could potentially unfreeze the video. I still have no reliable way to cause such a freeze to test this though. This is also more of a workaround, I would eventually like to fix the freezing entirely.

**Comment by Hexnet111** [comment] 2021-01-12 22:45
While I would be happy to help and test to see if the freezing problem is still there, my sanity might not last if I play the shrek movie again. lol

**Comment by Hexnet111** [comment] 2021-01-12 22:46
> If I understand correctly your issue is with the color blending, which causes bright lighting from the map to drown out darker colors in the video. I experimented a bit trying to implement a variable amount of color blending, but that didn't quite work out how I would have liked. The only option I have would be to add a mode that completely disables blending, and that looks pretty terrible as well.
> 
> I added contrast and brightness controls to the mod for a different request, those might also work in this case. Increasing brightness and decreasing contrast both would boost the darker colors of the movie. Still more of a workaround, but it probably beats having to re-render the video to turn black into blue.
> 
> Regarding the freezing issue I wonder if that is mitigated now, since I recently implemented a re-syncing mechanism for cases where the video drifts out of sync. A freeze might cause a re-sync to occur, which could potentially unfreeze the video. I still have no reliable way to cause such a freeze to test this though. This is also more of a workaround, I would eventually like to fix the freezing entirely.

While I would be happy to help and test to see if the freezing problem is still there, my sanity might not last if I play the shrek movie again. lol

**Comment by Kevga** [comment] 2021-02-26 16:30
I found some time to try to reproduce this issue. I watched about one hour of a concert recording in Beat Saber. The video was an H.264 encoded mp4 file with a 4K resolution and a size of about 17 GB. I didn't notice any freezing, stuttering or de-syncing at all, the playback was basically flawless. The logs didn't show any signs of problems either. I can only assume that playback issues you experienced may be related to a faulty video file, or some special circumstance that didn't trigger for me.

In any case, Cinema uses the built-in Unity video player to decode and render the video, so any freezing that may occur is likely a problem with that video player component. Cinema only tells Unity which video file to load and then starts the playback. After that point, Cinema is no longer involved with playback at all. That means that I would very likely be unable to fix the issue, except for using a completely different video player, as alluded to in an earlier comment.

I will be closing this for now, as I am unable to reproduce it. If anyone finds this issue in the future and is still affected by this, please leave a comment.

**Closed by Kevga** 2021-02-26 16:30 UTC
Labels: bug
